name: fluttercouch_example
description: Demonstrates how to use the fluttercouch plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  scoped_model: ^0.3.0
  fluttercouch:
    path: ../

flutter:
  uses-material-design: true