name: fluttercouch
description: With Fluttercouch is possible to use Couchbase Mobile Native SDK in Flutter Projects.
version: 1.0.0
author: Luca Christille
homepage: "https://github.com/oltrenuovefrontiere/fluttercouch"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: it.oltrenuovefrontiere.fluttercouch
    pluginClass: FluttercouchPlugin
